version: 2.1
executors:
  golang:
    docker:
      # Whenever the Go version is updated here, .promu.yml, Dockerfile and line 6 of this file should also be updated.
      - image: cimg/go:1.22
jobs:
  test:
    executor: golang
    steps:
      - checkout
      - run: make test
  build:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_promu
      - run: ./promu crossbuild
      - run: ./promu crossbuild tarballs
      - run: ./promu checksum .tarballs
  release:
    executor: golang
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_promu
      - run: ./promu crossbuild
      - run: ./promu crossbuild tarballs
      - run: ./promu checksum .tarballs
      - run: ./promu release .tarballs
workflows:
  version: 2
  build_and_release:
    jobs:
      - test
      - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
